### ISSUE TITLE
Nice plugin

### ISSUE THREAD

**Issue by aspark21** [sharpchi/moodle-local_accessibilitytool#1]
Just wanted to give some kudos for sharing this nice plugin.

A bit unclear about what this would allow though as not mentionned in the readme - https://github.com/sharpchi/moodle-local_accessibilitytool/blob/master/samples/theme/classes/format_grid_renderer.php

And also a heads up, I've looked at implementing this into the Adaptable theme and have submitted a merge request for it - https://gitlab.com/jezhops/moodle-theme_adaptable/merge_requests/12 

Apparently that page is not public though but diff is here - https://gitlab.com/aspark21snow/moodle-theme_adaptable/compare/master...accessibilitytool-clean

So this plugin might pick up a wider user base soon :)

**Comment by sharpchi** [comment]
One of the settings for user's settings is to flatten the Grid course format. We found that Grid didn't play well with screen readers, so the sample class basically renders any grid formatted courses as a basic topic format.

The idea is that you copy the format_grid_renderer.php file into your theme's classes directory. If you've already got something overriding the grid renderer, just copy in the relevant code.

Hope this helps by way of an explanation.
