### ISSUE TITLE
Colours not applying consistently on Open Dyslexic font

### ISSUE THREAD

**Issue by aspark21** [sharpchi/moodle-local_accessibilitytool#5]
Related to #3 feature introduction:

Here's what a sample of "normal site"
<img width="347" alt="Screenshot 2020-03-09 at 16 24 42" src="https://user-images.githubusercontent.com/4015496/76235106-8d76ba80-6222-11ea-965f-a78df93df8c2.png">

Here's with Mono font
<img width="378" alt="Screenshot 2020-03-09 at 16 24 51" src="https://user-images.githubusercontent.com/4015496/76235189-ab441f80-6222-11ea-849c-8bd589d8a18a.png">

And with Open Dyslexic font:
<img width="394" alt="Screenshot 2020-03-09 at 16 24 59" src="https://user-images.githubusercontent.com/4015496/76235226-b6974b00-6222-11ea-8c66-b8f306aa23ca.png">

For some reason it mostly defaults back to black, though I can't see anything obvious in the html why it even is black.

cc @evesucl

**Comment by sharpchi** [comment]
The only time I change the font colour is if the contrast settings have been changed (e.g. black on yellow). I wonder if you have something specific in your theme for the classes I inject into the body element.

**Comment by aspark21** [comment]
Should have mentioned colour doesn't change with the alternative contrasts either. End up with black text on black background for yellow on black.

This is a few commits away from our live theme - https://gitlab.com/aspark21snow/moodle-theme_adaptable/-/tree/accessibilitytool

**Comment by sharpchi** [comment]
I've installed your theme and switched to the accessibilitytool branch. Out of the box, the menu looks like this:
![image](https://user-images.githubusercontent.com/3774280/76296674-71205f80-62ae-11ea-8015-1ffc7b42b660.png)
This is the same for all fonts
![image](https://user-images.githubusercontent.com/3774280/76296714-88f7e380-62ae-11ea-9d7c-896e9a7434ac.png)

If I switch contrast the colours change as I would expect:
![image](https://user-images.githubusercontent.com/3774280/76296880-ceb4ac00-62ae-11ea-8252-68870aa3a3f8.png)

I can change the menu colours in adaptable:
![image](https://user-images.githubusercontent.com/3774280/76297205-5995a680-62af-11ea-9df7-60ca579b5a2c.png)
And these are reflected as I would expect with the default contrast setting:
![image](https://user-images.githubusercontent.com/3774280/76297251-77630b80-62af-11ea-9139-cc37e8087aca.png)
And when I change the contrast the font colours change too.
![image](https://user-images.githubusercontent.com/3774280/76297326-8fd32600-62af-11ea-8126-2035b8686535.png)

Accessibility tool only changes the font colours when the contrast setting is set to something other than default.
The only thing I can think is that there's some other styling somewhere that's affecting this. But I'm not able to reproduce the issue you seem to be having.

**Comment by sharpchi** [comment]
Maybe you're looking it the wrong way round, you said "For some reason it mostly defaults back to black, though I can't see anything obvious in the html why it even is black." perhaps there's something that's changing the default black to white for the other fonts in your theme or theme settings.

**Comment by aspark21** [comment]
Thanks Mark for taking a look.

I’ll test more thoroughly with our settings once I’m back from leave

**Comment by aspark21** [comment]
So I thought I was going mad and then thought it had to be something simple - turns out this works fine in Safari but it does not work in Chrome. Since I'm mainly in Chrome, that's why I couldn't see the same as you.

This is in Safari:

<img width="1194" alt="Screenshot 2020-03-24 at 22 33 32" src="https://user-images.githubusercontent.com/4015496/77483242-91f4c300-6e1f-11ea-899b-8c908eaa63f6.png">


This is in Chrome:

![Screenshot 2020-03-24 at 22 32 09](https://user-images.githubusercontent.com/4015496/77483271-afc22800-6e1f-11ea-9fd6-d649b68f8778.png)

Same user, same page, same settings

**Comment by dragos5436** [comment]
Issue has now been fixed, the font colour no longer defaults to black. Tested on Chrome, Firefox and Edge

**Comment by aspark21** [comment]
In light of Dragos's testing, marking as resolved. Not clear how it got fixed but glad it is :)
